### ISSUE TITLE
Template does not start on Glitch

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/botkit-template#12]
Error: Missing required parameter `public_address`
    at new WebexAdapter (/rbd/pnpm-volume/5a1b8106-5ade-47bb-8046-c2f1c19b587d/node_modules/.registry.npmjs.org/botbuilder-adapter-webex/1.0.4/node_modules/botbuilder-adapter-webex/lib/webex_adapter.js:114:23)
at Object.<anonymous> (/app/bot.js:72:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ObjectIsAdvantag** [comment]
note: the monitor skill fails on Glitch as it uses the PUBLIC_ADDRESS env variable,
